spring.application.name=eventsphere

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE}
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.idle-timeout=600000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true



jwt.secret=${JWT_SECRET}
jwt.short.expiration=${JWT_SHORT_EXPIRY}
jwt.refresh.expiration=${JWT_LONG_EXPIRY}

supabase.s3.endpoint=${SUPABASE_S3_ENDPOINT}
supabase.s3.access-key=${SUPABASE_S3_ACCESS_KEY}
supabase.s3.region=${SUPABASE_S3_REGION}
supabase.s3.secret-key=${SUPABASE_S3_SECRET_KEY}
supabase.s3.bucket-name=${SUPABASE_S3_BUCKET_NAME}

spring.servlet.multipart.max-file-size=${MULTIPART_FILE_MAX_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_REQUEST_MAX_SIZE}

global.max-file-size=${GLOBAL_FILE_MAX_SIZE}

admin.default.username=${ADMIN_DEFAULT_USERNAME}
admin.default.email=${ADMIN_DEFAULT_EMAIL}
admin.default.password=${ADMIN_DEFAULT_PASSWORD}
admin.default.phone=${ADMIN_DEFAULT_PHONE}
admin.default.cnic=${ADMIN_DEFAULT_CNIC}
admin.default.pic=${ADMIN_DEFAULT_PIC}

spring.data.redis.url=${REDIS_URL}

spring.jpa.open-in-view=false